### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by datthanhvu98** [antonwierenga/activemq-cli#1]
Failed to connect to Broker: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
    java.net.ConnectException: Connection refused]

**Comment by antonwierenga** [comment]
This is the error you get when you run the command ```connect --broker local``` when there's no (JMX enabled) broker running locally. Do you have a broker running locally?

You can start an embedded broker by running the command ```start-embedded-broker```. Then you should be able to connect to it by running the command ```connect --broker local```

**Comment by datthanhvu98** [comment]
i solved this prolem . Run Terminal : Jconsole then run new window terminal
: start --broker namebroker . In Jconsole window paste url jmx and run .
The end , run code : connect --broker namebroker


2016-09-05 2:49 GMT+07:00 antonwierenga <notifications@github.com>:

**Comment by datthanhvu98** [comment]
vlance.vn
    
    
        
        
            
                
                    
                        
                    
                
            
        
         
        
        
                
        
        
            
                
                    Bạn vừa nhận được lời mời tham gia vLance, nhận tới 450.000 VNĐ*
                
                Dat Thanh Vu mời bạn tham gia vLance:
                
                    
                
                
                    "Bạn có thể tìm kiếm việc làm hoặc thuê những chuyên gia để thực hiện công việc với một chi phí hợp lý"
                
                
                    *Tham gia vLance và nhận ngay quà tặng lên tới 30 Credit (trị giá 450.000 VNĐ) ngay khi dự án đầu tiên của bạn được hoàn thành.
                
                
                    
                        Nhận quà tặng
                    
                
            
        
    
                        
        
        
            
                
                    You've just received an invitation to join vLance, receive up to 450.000 VND*
                
                Dat Thanh Vu  is inviting you to vLance: 
                
                    
                
                
                    "You can find jobs or hire professionals to work for you at a reasonable price"
                
                
                    *Join vLance and receive a gift of up to 30 Credit which equal 450.000 VND once your first project is completed. 
                
                
                    
                        Accept gift
                    
                
            
        
    
                    
        
        
        
        
            
                
                    
                        Bạn cần trợ giúp? Liên hệ với chúng tôi
                        Email: hotro@vlance.vn
                        Tel: 04-6684-1818
                    
                    
                        
                            
                        
                        
                            
                        
                        
                            
                        
                        
                            
                        
                    
                
                
                    © 2013 - 2016 vLance.vn 
                    Địa chỉ: Phòng 306, Tầng 3, Tòa nhà GP.Invest, số 170 Đường La Thành, quận Đống Đa, Hà Nội.
