### ISSUE TITLE
Unable to connect broker

### ISSUE THREAD

**Issue by guna144** [antonwierenga/activemq-cli#12]
Hi Anton Wierenga,
I try to connect broker as per the video, which is for connecting broker and work with activemq cli.
bun I am unable do that. when i connect like this >connect --broker local
"Broker not found"  I am getting this error. Please advise me how to resolve this error

**Comment by antonwierenga** [comment]
A 'Broker not found' error is given when the specified broker ('local') is not defined in activemq-cli.config. 

Broker 'local' is defined by default with activemq-cli and works with the embedded broker:

<img width="422" alt="screen shot 2018-09-04 at 06 38 41" src="https://user-images.githubusercontent.com/14827290/45010626-d38c0600-b00e-11e8-85ff-c80193f77958.png">
