### ISSUE TITLE
Queues of another broker

### ISSUE THREAD

**Issue by edouardlauer** [antonwierenga/activemq-cli#13]
Hello,

I've 3 brokers on the same server (test, preprod and prod). Whatever broker I try to list the queues I only get the list of the test broker. Here my config file:
broker {
    test {
        amqurl = "ssl://localhost:61617"
        jmxurl = "service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi"
        username = ""
        password = ""
        keyStore = "test_client.ks"
        keyStorePassword = ""
        trustStore = "test_client.ts"
        prompt-color = "yellow"
    }

    preprod {
        amqurl = "ssl://localhost:61618"
        jmxurl = "service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi"
        username = ""
        password = ""
        keyStore = "preprod_client.ks"
        keyStorePassword = ""
        trustStore = "preprod_client.ts"
        prompt-color = "green"
    }

    prod {
        amqurl = "ssl://localhost:61619"
        jmxurl = "service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi"
        username = ""
        password = ""
        keyStore = "prod_client.ks"
        keyStorePassword = ""
        trustStore = "prod_client.ts"
        prompt-color = "red"
    }

}

Whatever I'm doing I'm always getting connected to the test broker.

![2019-03-21_09-41-43](https://user-images.githubusercontent.com/48787655/54741214-0ae28e80-4bbe-11e9-8daf-8b8658a0ceb3.png)

**Comment by edouardlauer** [comment]
Please note version that I'm using v0.6.0

**Comment by antonwierenga** [comment]
Commands like 'list-queues' and 'info' retrieve information from JMX using the configured jmxurl. The jmxurl of all your brokers are the same (service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi) and looks to point to the 'test' broker.

Try to [configure](http://activemq.apache.org/jmx.html) your brokers with different jmx ports (<managementContext connectorPort="1099") and update your activemq-cli config respectively.

**Comment by edouardlauer** [comment]
Hello,

you were right. After modifying the JMX ports everything works well.

Many thanks,
Edouard
