### ISSUE TITLE
Export not containing message details

### ISSUE THREAD

**Issue by marcosmoreno** [antonwierenga/activemq-cli#15]
Hi, 
congrats on a wonderful tool.
When exporting messages to an external file, the "message details" is not included. We have some zipped information there that is important.  
The interface shows no errors when doing the export. If I move the messages to other queue things are there, but if  I export/import they vanish.
Is there a way to export/import this information as well?

**Comment by antonwierenga** [comment]
Hi,

At the moment activemq-cli supports text messages (javax.jms.TextMessage) only.
You cannot send or export messages with binary data.

Regards,

Anton
