### ISSUE TITLE
SSL and Keystore not supported

### ISSUE THREAD

**Issue by Subtalime** [antonwierenga/activemq-cli#2]
any chance of adding this to the project? Our AMQs are using this for security.

**Comment by antonwierenga** [comment]
I created v0.2.0 for this. You can now specify keyStore, keyStorePassword and trustStore in the broker configuration (activemq-cli.config). For example:

```
  local {
    amqurl = "ssl://localhost:61616"
    jmxurl = "service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi"
    keyStore = "~/client.ks"
    keyStorePassword = "secret"
    trustStore = "~/client.ts"
  }   
```
