### ISSUE TITLE
mirror queue is not getting deleted after messages are exported

### ISSUE THREAD

**Issue by vikas61993** [antonwierenga/activemq-cli#20]
if we run below command when the amq queues are high it just hangs and does nothing 

export-messages --queue queuename --file filename

**Comment by antonwierenga** [comment]
Hi, 

I can you specify 'high'? I have no problem sending and exporting 100K messages. The export-messages command creates a copy of the queue you want to export and subsequently consumes and writes these messages to file.

You can monitor the progress of the export-messages command by opening another activemq-cli and use the list-queues command to see how many messages are still in the mirror queue. If the export-messages command is aborted before it finishes, the mirror queue is not deleted. You can safely delete it with the remove-queue command.
![Screenshot 2020-08-31 at 09 38 42](https://user-images.githubusercontent.com/14827290/91695057-deca8b80-eb6d-11ea-8504-94daee5c544c.jpg)
