### ISSUE TITLE
connexion issue, hostname, dns...

### ISSUE THREAD

**Issue by 8mccm8** [antonwierenga/activemq-cli#21]
Hi,

When I setup directly an IP in the config file:

`prod {  
	    amqurl = "tcp://10.10.10.10:62611"  
		jmxurl = "service:jmx:rmi:///jndi/rmi://10.10.10.10:1099/jmxrmi"  
		username = ""  
		password = ""  
		prompt-color = "light-blue" // Possible values: "gray", "red", "light-red", "light-green", "green", "light-yellow", "yellow", "light-blue", "blue", "light-purple", "purple", "light-cyan", "cyan", "light-white", "white"  
	}  `

it try to resolve the hostname of the server:

`activemq-cli>connect --broker prod
Failed to connect to broker: Unknown host: srvamq1; nested exception is:
    java.net.UnknownHostException: srvamq1
activemq-cli>`

but it works when my hosts file resolve the hostname

`activemq-cli>connect --broker prod
Connected to broker 'prod'
prod>`

thanks

**Comment by antonwierenga** [comment]
Hi,

Can you try configuring java.rmi.server.hostname for your ActiveMQ broker? (in your case: java.rmi.server.hostname=10.10.10.10).

See also:
https://github.com/antonwierenga/activemq-cli/issues/9
