### ISSUE TITLE
Broker Not Found

### ISSUE THREAD

**Issue by eddieyeeinsight** [antonwierenga/activemq-cli#22]
I'm testing the activemq-cli client with RedHat AMQ7, hitting the jmxrmi and after it authenticates, the client responds with "Broker not found"

Running Redhat AMQ Broker 7.9.4.   Internal paths changed perhaps?   The activemq-cli was working fine with jboss amq 6, but we're trying to upgrade and running into connection issues.

Thanks!

**Comment by antonwierenga** [comment]
It looks as if the JMX object name of the broker has changed in Redhat AMQ Broker 7.9.4. 
activemq-cli assumes the following object name:
org.apache.activemq:type=Broker,brokerName=[SOME_BROKER_NAME]

Do you know what the object name of the broker is in Redhat AMQ Broker 7.9.4?

**Comment by eddieyeeinsight** [comment]
It looks like it is org.apache.activemq.artemis

See attached screenshot:

**Comment by eddieyeeinsight** [comment]
I just tested it with the 0.9.1 version and it looks like it is still complaining that the broker not found.   I took a look at the JMX configuration on Redhat's AMQ6 and it is quite different. (see screenshots).  
![RHAMQ6](https://user-images.githubusercontent.com/28320577/173426272-d1eb15f9-2de4-43cf-a5a3-42449b366953.jpg)
![RHAMQ7](https://user-images.githubusercontent.com/28320577/173426277-4d8623f2-5b1d-4fd9-afa9-af097281c727.jpg)

**Comment by antonwierenga** [comment]
You're right; supporting the jmx domain is not enough. Even if activemq-cli finds the broker I wonder if activemq-cli is compatible with artemis. Unfortunately I don't have the time to investigate this short term. In case you're a developer yourself; you can try to modify [this code](https://github.com/antonwierenga/activemq-cli/blob/563e2c0609d22b4f54c946ce068dae6a604d038a/src/main/scala/activemq/cli/command/Commands.scala#L162) to fix the jmx lookup and see how far that brings you.
