### ISSUE TITLE
The selector of Active MQ can only select among the first 200 messages

### ISSUE THREAD

**Issue by Aaron-PanJi** [antonwierenga/activemq-cli#24]
### Suggested reasons
Since the response message does not have an expiration time, if the requester does not receive the response message within 2 seconds, the server will send the response message back to the response queue. This message will never be consumed and will always be backlogged in the queue; if this There are many cases, which may cause a large backlog of messages.
According to the analysis, it is found that if the response queue has more than 200 backlog messages, subsequent requests will never receive a response message, even if the corresponding response message has returned to the corresponding queue within two seconds, which will cause the entire queue to be stuck Phenomenon.

**Comment by antonwierenga** [comment]
Like [your other issue](https://github.com/antonwierenga/activemq-cli/issues/25) this issue also seems to be related to the activemq broker itself, not activemq-cli.
