### ISSUE TITLE
The number of consumers in the response queue reaches tens of thousands and will not be released, and the broker process cannot be stopped normally

### ISSUE THREAD

**Issue by Aaron-PanJi** [antonwierenga/activemq-cli#25]
### Suggested reasons
After the program runs for a period of time, it is found that there are tens of thousands of consumers in the response queue, and they will not be released. Subsequent messages are blocked and cannot be received. The integrated broker runs very slowly, the memory is almost exhausted, and the broker process cannot be stopped normally

**Comment by antonwierenga** [comment]
Hi Aaron,

The problem you are describing sounds like a broker issue not an issue of activemq-cli. 
Although you connect to a broker with activemq-cli using 'connect --broker' activemq-cli is not constantly connected to the broker. For every command you execute activemq-cli connects, executes the command and then disconnects.
activemq-cli will also not consume your application queues; some commands (e.g. list-messages, export-messages) will create a copy of the queue and then consume those messages. Is it possible another application connected to the broker is adding consumers to your response queue?
