### ISSUE TITLE
Fails to connect

### ISSUE THREAD

**Issue by N4TY** [antonwierenga/activemq-cli#3]
Correctly configured the admin and password in conf/activemq-cli.config, but when I try to connect to my "local" activemq broker using
    connect --broker local
I get this console message:
    "Failed to connect to broker: User name [admin] or password is invalid."

Now, the ID/PW is KNOWN to be correct, so not sure what's wrong.

Thanks, Tyler

**Comment by antonwierenga** [comment]
Hi Tyler,

Are you running the activemq web console?
If so; can you check if you are able to login and send a message to a queue from the web console?

I know of one user who encountered this error who was able to resolve this by adding activemq variables to the /etc/default/activemq configuration file (as described [here](http://activemq.2283324.n4.nabble.com/SecurityException-User-name-admin-or-password-is-invalid-td4707715.html).

Regards,

Anton
