### ISSUE TITLE
Running cli on OSX prints error about realpath then kills terminal

### ISSUE THREAD

**Issue by mikeycmccarthy** [antonwierenga/activemq-cli#6]
I'm trying to run this in OSX using iTerm2. I get the same error about 'realpath' then the terminal is closed. Thanks for any help as it looks like a really useful tool.

**Comment by mikeycmccarthy** [comment]
```
realpath:17: = not found
```
is the exact message

**Comment by antonwierenga** [comment]
It should not be a problem to run activemq-cli on OSX with iTerm2. However for some reason the generated startup script does not work for you.
Can you try the following: open iTerm and navigate to the activemq-cli directory and then run the following command:

java -cp ./lib/com.antonwierenga.activemq-cli-0.4.0.jar:\
./lib/org.scala-lang.scala-library-2.11.6.jar:\
./lib/org.springframework.shell.spring-shell-1.1.0.RELEASE.jar:\
./lib/commons-io.commons-io-2.3.jar:./lib/jline.jline-2.11.jar:\
./lib/com.google.guava.guava-15.0.jar:./lib/cglib.cglib-2.2.2.jar:\
./lib/asm.asm-3.3.1.jar:\
./lib/org.springframework.spring-context-support-4.0.3.RELEASE.jar:\
./lib/org.springframework.spring-beans-4.0.3.RELEASE.jar:\
./lib/org.springframework.spring-core-4.0.3.RELEASE.jar:\
./lib/commons-logging.commons-logging-1.1.3.jar:\
./lib/org.springframework.spring-context-4.0.3.RELEASE.jar:\
./lib/org.springframework.spring-aop-4.0.3.RELEASE.jar:\
./lib/aopalliance.aopalliance-1.0.jar:\
./lib/org.springframework.spring-expression-4.0.3.RELEASE.jar:\
./lib/org.apache.activemq.activemq-all-5.13.1.jar:\
./lib/com.typesafe.config-1.2.1.jar:\
./lib/org.scala-lang.jline-2.11.0-M3.jar:\
./lib/org.fusesource.jansi.jansi-1.4.jar:\
./lib/org.scala-lang.modules.scala-xml_2.11-1.0.3.jar\
 activemq.cli.ActiveMQCLI
