### ISSUE TITLE
Dump STOMP message from a specific queue

### ISSUE THREAD

**Issue by rakare2015** [antonwierenga/activemq-cli#7]
Hi, 

Am not sure where to contact for new feature. Am looking feature to dump all the STOMP messages from the specific queue. Is there any way to perform this using activemq cli? I see it export message from JMX queue only not for STOMP messages.

**Comment by antonwierenga** [comment]
Although I have only tested and used ActiveMQ CLI using the default OpenWire protocol it is not restricted to this specific wire level protocol. ActiveMQ CLI does require a JMX enabled ActiveMQ broker to function properly.

**Comment by rakare2015** [comment]
Thanks! I see the in the config I should mentioned like below URL format to connect with JMX, 

jmxurl = "service:jmx:rmi://localhost:1098/jndi/rmi://localhost:1099/jmxrmi"

So what URL format I should use if I want to connect it through STOMP protocol on the port 61613?

**Comment by antonwierenga** [comment]
amqurl = "tcp://localhost:61613"

"Starting with 5.13.0 ActiveMQ has support for automatic wire protocol detection over TCP, SSL, NIO, and NIO SSL.  OpenWire, STOMP, AMQP, and MQTT are supported.  For details see the AUTO Transport Reference."

**Comment by rakare2015** [comment]
I tried 'amqurl = "tcp://<server-name>:61615"' this but its not connecting and getting below message,

Failed to connect to broker: Wire format negotiation timeout: peer did not send his wire format.

Below is stomp configuration on activemq.xml

      <transportConnector name="stomp+nio" uri="stomp+nio://0.0.0.0:61615"/>

When I change the amqurl to connect with 61616 it works but not getting stomp message.

**Comment by antonwierenga** [comment]
I am afraid I cannot help you here. Maybe [activemq's built-in browse task](http://activemq.apache.org/activemq-command-line-tools-reference.html) will let you read the messages.
